### ISSUE TITLE
Databricks - Consider Mount Path instead of Cluster Settings

### ISSUE THREAD

**Issue by ezwiefel** [Microsoft/MCW-Big-data-and-visualization#2]
It would be nice to highlight `dbutils.fs.mount()` functionality

**Comment by joelhulen** [comment]
I went back and forth on this one, as it didn't seem to matter which method to use for the lab. If you think it makes a difference, I can change it.

**Comment by ezwiefel** [comment]
I'd like to hear what others think... my thought was that it is nice to show off the feature and it's a pretty nice feature.

Overall, though, I don't have a strong opinion about it - that's why I'd like to hear what others think.

**Comment by nabeelderhem** [comment]
Not the expert here, but I think we can point it out at least.

**Comment by joelhulen** [comment]
I will mention it. However, I'm not adding it for two reasons:

1. I don't like the idea of having the storage account key saved to the notebook. I would normally have it set via a widget, but then the ADF activity would need to pass in the account key which also doesn't make sense. Having this done during the cluster setup makes most sense.

2. We have to use a slightly older version of Databricks for the cluster (for now), due to the Spark version that's loaded in the DSVM. The mount command is different in that version.
