### ISSUE TITLE
Databricks cluster version not available.

### ISSUE THREAD

**Issue by chmitch** [Microsoft/MCW-Big-data-and-visualization#20]
The directions specify creating a Databricks 3.4 cluster specifically due to the spark version installed on the data science vm; however the lowest cluster version we can create is 3.5 LTS.

The documentation should be updated to reflect either a higher version of the Databricks cluster, and if necessary update the DSVM to a higher version of Spark to match.

**Comment by joelhulen** [comment]
I was afraid the required Databricks cluster version would eventually phase out, but not this soon. Hopefully the DSVM images will be updated soon to include a newer version of Spark. Previous attempts to manually update Spark on the DSVM failed, due to customizations made to the Spark instance (at the file level) to work with the Spark ML CLI enhancements. I'll follow up with the team that manages the DSVM to see what their plans are to update the pre-installed Spark version.

**Comment by chmitch** [comment]
The current DSVM build appears to be running Spark 2.3.0 with Scala 2.11.8 which appears to be compatible with data bricks 4.1.  I'm still testing, but if this scenario does indeed work should I update the scenario and submit a pull request?
