### ISSUE TITLE
May 2019 - Scheduled content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Big-data-and-visualization#55]
Hello,
This workshop is scheduled for a content update.  Please review the workshop and current open issues and give update suggestions.

Please include field request to add Azure Data Lakes as a storage solution to the workshop.

Thanks,
Dawnmarie

**Comment by joelhulen** [comment]
Here are my update suggestions:

1. Refactor DBC files to either split into two separate files to import, or clarify which Exercise/Task is related to which notebook
2. Move instructions for copying required keys (storage, etc.) into the step-by-step doc from the before the HoL doc. This will help in cases where students are working in a pre-provisioned lab environment
3. Move from using Blob storage to ADLS Gen2 in the WDS and lab

**Comment by Mmodarre** [comment]
Here are my initial update suggestions:

1. Inline with our Modern DW reference architecture, The architecture should include a form of RDBMS (either SQLDB or SQLDW) as the serving layer to PowerBI rather than connecting Azure Databricks directly to PowerBI.

2. I would stick with Blob storage and mounting it in the cluster rather than using ADLS Gen2 although a reference to ADLS Gen2 differences and when an architecture would benefit most from it would be really good. First of all mounting blob storage is much easier and straight forward than ADLS Gen2 in Azure Databricks, also it is an opportunity to emphasize that ADLS gen2 (and hence the extra cost) is not always the choice for big data solutions when the hierarchical name space and ACLs are not required.

**Comment by joelhulen** [comment]
I like your suggestions.

1. For this one, another pattern that is becoming more common is to use Azure Analysis Services as the serving layer for Power BI. In this case, you would have to synchronize the data to your semantic models in Azure Analysis Services.

2. Using ADLS Gen2 is a request from one of the SMEs. Agree that having a hierarchical namespace isn't always necessary, but one of the rationales was because of the better performing connector ADLS Gen2 uses. I'll leave this up for you and the other SMEs to decide.

**Comment by saurius** [comment]
About ADLS Gen2 it should be included or if not it should be explained why for this case is not the best solution since attendees now always ask about it.

**Comment by swan-am-i** [comment]
> Here are my update suggestions:
> 
> 1. Refactor DBC files to either split into two separate files to import, or clarify which Exercise/Task is related to which notebook
> 2. Move instructions for copying required keys (storage, etc.) into the step-by-step doc from the before the HoL doc. This will help in cases where students are working in a pre-provisioned lab environment
> 3. Move from using Blob storage to ADLS Gen2 in the WDS and lab

I agree, we need to show how best to secure the data as that is the first battle we must win with the customer!

**Comment by joelhulen** [comment]
@swan-am-i @saurius @Mmodarre I would like to conclude the list of updates I'll be working on, since there has been some differences in opinion here as to which updates we should make.

I ran the WDS for this last week at the partner boot camp, and we had a great discussion on whether ADLS Gen2 is appropriate for the customer use case vs. blob storage. It was apparent that, due to the low storage requirements, lack of need for ACLs or hierarchical namespace, and given the size of the data and the speed in which they are processed, that blob storage was the better choice. That said, I suggest we keep using blob storage, but deepen the conversation about why and when to use ADLS instead. We have MCWs that use ADLS Gen2, such as the Cosmos DB one. ADLS makes most sense for the customer in that scenario. We ran both WDS's, which allowed us to compare and contrast.

Can we please agree on the following updates?

1. Refactor DBC files to either split into two separate files to import, or clarify which Exercise/Task is related to which notebook
2. Move instructions for copying required keys (storage, etc.) into the step-by-step doc from the before the HoL doc. This will help in cases where students are working in a pre-provisioned lab environment
3. Continue using blob storage, but deepen the discussion about blob storage vs. ADLS and when it is appropriate to choose one over the other
4. Add Azure Analysis Services as the serving layer for Power BI, as opposed to directly connecting to Databricks. (This update will be to the WDS only, so as not to add more complexity to the lab)
5. Update the AML components of the architecture based on new AML features, such as AutoML
6. Replace the DataGuise portion with Databricks-related security discussion

Please let me know ASAP if you agree with this final list of updates.

**Comment by swan-am-i** [comment]
@joelhulen  - I like this idea and agree with the use of blob here. We should leverage the ADLS best practices in a different customer scenario.  We want to show the right use of these technologies in real world scenarios

**Comment by joelhulen** [comment]
I have completed a draft of the June update for your review.

All items were addressed. I modified one item in the list: "Add Azure Analysis Services as the serving layer for Power BI" to "Add Azure SQL Database as the serving layer for Power BI", per @Mmodarre's suggestion. This is because the Databricks Spark connector is not yet supported in ADLS.

**Comment by DawnmarieDesJardins** [comment]
Closing issue, addressed in June 2019 update.
